spring.application.name=versequill
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/versequill_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Logging implimentation

# Set logging level
logging.level.root=INFO

# Disable console logging
logging.console.enabled=false

# Log file path and name
logging.file.name=D:/logs/verseQuill/app.log

# Log file max size & rotation (Spring Boot 2.2+)
logging.file.max-size=10MB
logging.file.total-size-cap=100MB
logging.file.max-history=7
